export const MOCK_TERMINAL_EVENTS = [
  { delay: 300, text: '$ kosmic scrape https://members.example.org', category: 'INPUT' },
  // Anti-bot setup (real measures)
  { delay: 600, text: '→ Launching headless browser...', category: 'BROWSER' },
  { delay: 400, text: '→ Stealth: navigator.webdriver patched', category: 'BROWSER' },
  { delay: 300, text: '→ Stealth: WebGL → Intel Iris OpenGL Engine', category: 'BROWSER' },
  { delay: 300, text: '→ Stealth: Sec-CH-UA headers injected', category: 'BROWSER' },
  { delay: 400, text: '→ TLS fingerprint: chrome136 (JA3 rotated)', category: 'BROWSER' },
  { delay: 500, text: '→ Anti-bot ready ✓', category: 'SYSTEM' },
  { delay: 200, text: '', category: 'SYSTEM' },
  // Scrape flow
  { delay: 600, text: '→ Navigating to https://members.example.org', category: 'NAV' },
  { delay: 1200, text: '→ AI analyzing page structure...', category: 'PARSE' },
  { delay: 800, text: '→ Found member directory — learning selectors from 3 samples', category: 'PARSE' },
  { delay: 1000, text: '→ Selectors learned: name, email, phone, address ✓', category: 'PARSE' },
  { delay: 400, text: '→ Extracting page 1... 50 records', category: 'CAPTURE' },
  { delay: 500, text: '→ Pagination detected: clicking "Next →"', category: 'SCROLL' },
  { delay: 800, text: '→ Extracting page 2... 100 records captured', category: 'CAPTURE' },
  { delay: 500, text: '→ Extracting page 3... 150 records captured', category: 'CAPTURE' },
  { delay: 400, text: '→ Extracting page 4... 195 records captured', category: 'CAPTURE' },
  { delay: 600, text: '→ No more pages. Total: 195 member records', category: 'CAPTURE' },
  { delay: 300, text: '', category: 'SYSTEM' },
  { delay: 200, text: '── Phase 2: Enrichment ──', category: 'SYSTEM' },
  { delay: 300, text: '', category: 'SYSTEM' },
  { delay: 500, text: '→ 142 entries have websites, 53 need discovery', category: 'LOG' },
  { delay: 800, text: '→ Searching DuckDuckGo for 53 missing websites...', category: 'SEARCH' },
  { delay: 1200, text: '→ Found 31/53 websites via search', category: 'SEARCH' },
  { delay: 400, text: '→ Enriching 173 entries with 8 parallel workers...', category: 'LOG' },
  { delay: 600, text: '  [1/173] Acme Builders Inc — 2 emails, 1 phone, description, 3 social', category: 'DETAIL' },
  { delay: 200, text: '  [2/173] Bay Area Construction — 1 email, address, description', category: 'DETAIL' },
  { delay: 200, text: '  [3/173] Cedar Valley Homes — 3 emails, 2 phones, 4 social, est. 1998', category: 'DETAIL' },
  { delay: 150, text: '  ...', category: 'SYSTEM' },
  { delay: 800, text: '  [173/173] Zenith Contracting — 1 email, description, 2 social', category: 'DETAIL' },
  { delay: 300, text: '', category: 'SYSTEM' },
  { delay: 400, text: '✓ Done! 195 records → members_example_org_enriched.json', category: 'SYSTEM' },
  { delay: 200, text: '  Enriched: 156 | Failed: 17 | No website: 22', category: 'LOG' },
  { delay: 200, text: '  DuckDuckGo-discovered websites: 31', category: 'LOG' },
]

export const MOCK_RESULTS_JSON = {
  total: 195,
  enriched: 156,
  sample: [
    {
      company_name: 'Acme Builders Inc',
      website: 'https://acmebuilders.com',
      phone: '(555) 234-5678',
      contacts: [
        { name: 'John Smith', email: 'john@acmebuilders.com' },
        { name: null, email: 'info@acmebuilders.com' },
      ],
      description: 'Full-service general contractor specializing in commercial and residential construction since 1985.',
      social_media: {
        facebook: 'https://facebook.com/acmebuilders',
        linkedin: 'https://linkedin.com/company/acme-builders',
        instagram: 'https://instagram.com/acmebuilders',
      },
      street_address: '1234 Construction Ave, San Francisco, CA 94102',
      enrichment_status: 'enriched',
    },
    {
      company_name: 'Bay Area Construction',
      website: 'https://bayareaconstruction.com',
      phone: '(555) 876-5432',
      contacts: [{ name: null, email: 'contact@bayareaconstruction.com' }],
      description: 'Award-winning residential remodeling and new construction.',
      street_address: '567 Builder Blvd, Oakland, CA 94612',
      enrichment_status: 'enriched',
    },
  ],
}
